services:
  - type: web
    name: interior-backend
    env: node
    plan: free
    branch: main
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
